# Render Blueprint Specification
# Docs: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: iv-sentry-pro
    runtime: static
    buildCommand: ""
    staticPublishPath: ./
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
